### ISSUE TITLE
Implement Manual Login

### ISSUE THREAD

**Issue by mdwiltfong** [mdwiltfong/FlightTrackerCLI#9]
If a user wants to manually pass in their API Key, they should have an option to do so. At the moment the CLI is configured to do this by running.

`flighttracker login -m <apiToken>`

We can possibly store this API token locally through encryption. That way, the user doesn't have to keep inputing their API token. If not, we can also force the user to keep pasting their API token on each request.

**Comment by DeathAdderR** [comment]
I've been playing around with how to add the api key to the class. Since the class is being created after each command (unless I'm not understand how this program can work. In which case I'm eager to understand.) we would need to 'ask' if the api key has been entered into local storage when calling a method that requires the API key. In that case would we even need to add the API key to the class itself?

**Comment by mdwiltfong** [comment]
@DeathAdderR ,

That's the overall pattern that should implemented, but only in regards to BitWarden.

In hindsight, storing the API key locally in a `.json` file just isn't a good idea. Most CLIs leverage baked in software like Keychain on macOS, or Windows Credential Manager. I may close this issue and then reference it in another that discusses implementing those integrations in the CLI.

Also, this issue mentions pasting in the API Token directly into the terminal. I don't think that's a good idea still. If the computer is compromised, someone can review the terminal history and see that token.
